import os
import re

# :root {
#   --bg-color: #bfbec2;
#   --main-color: #553d94;
#   --caret-color: #523793;
#   --sub-color: #9f8ad4;
#   --sub-alt-color: #b5b0c2;
#   --text-color: #2e2e2e;
#   --error-color: #ca4754;
#   --error-extra-color: #7e2a33;
#   --colorful-error-color: #ca4754;
#   --colorful-error-extra-color: #7e2a33;
# }

variables = [
    "bg-color",
    "main-color",
    "caret-color",
    "sub-color",
    "sub-alt-color",
    "text-color",
    "error-color",
    "colorful-error-color"
]

optional_variables = [
    "error-extra-color",
    "colorful-error-extra-color"
]

def resolve_variable(var: str, css: str) -> str | None:
    m = re.search(f"--{var}:\\s*([^;]+);", css)
    if not m:
        return None
    res = m.group(1)
    # refers to another variable
    if res.startswith("var"):
        new_var = re.search(r"var\(--(.*)\)", res).group(1)
        return resolve_variable(new_var, css)

    return res

def parse_color(color_str: str) -> str:
    # take the first color of gradient
    if color_str.startswith("linear-gradient"):
        m = re.search(r"(#[0-9a-fA-F]+),", css)
        color_str = m.group(1)
    # expand 3-digit colors
    if len(color_str) == 4:
        color_str = "#" + color_str[1] * 2 + color_str[2] * 2 + color_str[3] * 2
  
    red = color_str[1:3]
    green = color_str[3:5]
    blue = color_str[5:7]
    
    return f"Color {{r: 0x{red}, g: 0x{green}, b: 0x{blue}}}"
    
        
def make_color_scheme_struct(filename: str, css: str) -> tuple[str, str, str]:
    base_name = os.path.splitext(filename)[0]
    static_name = base_name.upper().replace("-", "_")
    # avoid names that start with number
    if static_name[0].isdigit():
        static_name = "C_" + static_name
    display_name = base_name.replace("_", " ")
    lines = []
    
    # process variables
    for var in variables:
        m = resolve_variable(var, css)
        color_val = parse_color(m)
        lines.append(f"    {var.replace('-', '_')}: {color_val},")

    # process optional variables
    for var in optional_variables:
        m = resolve_variable(var, css)
        if m:
            color_val = parse_color(m)
            lines.append(f"    {var.replace('-', '_')}: Some({color_val}),")
        else:
            lines.append(f"    {var.replace('-', '_')}: None,")

    fields = "\n".join(lines)
    struct_code = f"pub static {static_name}: ColorScheme = ColorScheme {{\n{fields}\n}};"
    return static_name, display_name, struct_code

statics_found = []
all_struct_code = []

for filename in sorted([x for x in os.listdir("schemes") if x.endswith(".css")]):
    with open(os.path.join("schemes", filename), 'r') as f:
        css = f.read()
        s_name, d_name, code = make_color_scheme_struct(filename, css)
        all_struct_code.append(code)
        statics_found.append((d_name, s_name))

print("// Auto generated by monkeytype_color_schemes_to_rust.py")
print()
print("pub struct Color { r: u8, g: u8, b: u8 }")
print()
print("pub struct ColorScheme {")
for var in variables:
    print(f"    {var.replace('-', '_')}: Color,")
for var in optional_variables:
    print(f"    {var.replace('-', '_')}: Option<Color>,")
print("}\n")
for code in all_struct_code:
    print(code + "\n")

print(f"pub static SCHEMES: [(&str, &ColorScheme); {len(statics_found)}] = [")
for display_name, static_name in statics_found:
    print(f"    (\"{display_name}\", &{static_name}),")
print("];")
